// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3haDfYivn690zYFTikOgcL4ixWabA5h8',
    appId: '1:288448813875:web:6cb79c4e15c8673cb6fc46',
    messagingSenderId: '288448813875',
    projectId: 'zue-app',
    authDomain: 'zue-app.firebaseapp.com',
    storageBucket: 'zue-app.firebasestorage.app',
    measurementId: 'G-7HJT5QYMMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aPu4Vda6mXilE2TRE7DMgQ9eRXRuB74',
    appId: '1:288448813875:android:d99d433289074398b6fc46',
    messagingSenderId: '288448813875',
    projectId: 'zue-app',
    storageBucket: 'zue-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsU6BoiBEH673Ktth23xzWaZqrFpqbaYE',
    appId: '1:288448813875:ios:7101bef87be184eeb6fc46',
    messagingSenderId: '288448813875',
    projectId: 'zue-app',
    storageBucket: 'zue-app.firebasestorage.app',
    iosBundleId: 'com.example.zue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsU6BoiBEH673Ktth23xzWaZqrFpqbaYE',
    appId: '1:288448813875:ios:7101bef87be184eeb6fc46',
    messagingSenderId: '288448813875',
    projectId: 'zue-app',
    storageBucket: 'zue-app.firebasestorage.app',
    iosBundleId: 'com.example.zue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3haDfYivn690zYFTikOgcL4ixWabA5h8',
    appId: '1:288448813875:web:a6d9af973580048bb6fc46',
    messagingSenderId: '288448813875',
    projectId: 'zue-app',
    authDomain: 'zue-app.firebaseapp.com',
    storageBucket: 'zue-app.firebasestorage.app',
    measurementId: 'G-FBZXJRGJC1',
  );

}